spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/signal_db
    username: signal
    password: signal

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  batch:
    job:
      enabled: false
